sudo: false

language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - EK_TEST_PORT=8080

before_install:
  - make deps
  - make deps-test

script:
  - .travis/script.sh 7
