language: go

go:
  - 1.5.4
  - 1.6.2
  - tip

sudo: false

os:
  - linux
  - osx

env:
  - EK_TEST_PORT=8080

before_install:
  - go get -v pkg.re/check.v1
  - go get -v github.com/GeertJohan/go.linenoise

script:
  - .travis/script.sh .

after_success:
  - bash <(curl -s https://codecov.io/bash)
