language: go
go:
  - 1.4.2
  - 1.5.2
  - tip

sudo: false

os:
  - linux
  - osx
  - freebsd

env:
  - EK_TEST_PORT=8080

before_install:
  - go get pkg.re/check.v1

script:
  - .travis/script.sh .

after_success:
  - bash <(curl -s https://codecov.io/bash)
