language: go

go:
  - 1.4.3
  - 1.5.3
  - tip

sudo: false

os:
  - linux
  - osx
  - freebsd

env:
  - EK_TEST_PORT=8080

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v pkg.re/check.v1

script:
  - .travis/script.sh .

after_success:
  - bash <(curl -s https://codecov.io/bash)
