language: go

go:
  - 1.6.3
  - 1.7

sudo: false

os:
  - linux
  - osx

env:
  - EK_TEST_PORT=8080

before_install:
  - go get -v pkg.re/check.v1
  - go get -v pkg.re/essentialkaos/go-linenoise.v2

script:
  - .travis/script.sh .

after_success:
  - bash <(curl -s https://codecov.io/bash)
